spring:
  application:
    name: barter
  profiles:
    active: bookprofile
  flyway:
    enabled: true
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

server:
  port: ${APP_PORT:7000}

openlibraryapi:
  url: https://openlibrary.org/search.json
  coverImageUrl: https://covers.openlibrary.org/b/isbn
  baseurl: https://openlibrary.org
  isbnEndpoint: https://openlibrary.org/api/books
  bookshelfEndpoint: https://openlibrary.org/works/{id}/bookshelves.json
  timeout: 5000
  query:
    limit: 5
    fields: title,author_name,isbn,subject,want_to_read_count,currently_reading_count,already_read_count
    jscmd: details
    format: json

googleBooksApi:
  url: https://www.googleapis.com/books/v1/volumes
  timeout: 5000
  query:
    key: ${BOOKS_API_KEY}


cloudinary:
  cloud_name: dllr1e6gn
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}






